[package]
name = "telegram_sticker_batch_resizer"
version = "0.2.2"
authors = ["CatMe0w <catme0w@live.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
indicatif = "0.16.1"
