[package]
name = "telegram_sticker_batch_resizer"
version = "0.1.0"
authors = ["CatMe0w <catme0w@live.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"

[profile.release]
panic = 'abort'
