name: release-binaries

on:
  push:
    tags:
      - 'v[0-9]+.*'

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-musl
          use-cross: true

      - run: mv target/x86_64-unknown-linux-musl/release/telegram_sticker_batch_resizer target/x86_64-unknown-linux-musl/release/telegram_sticker_batch_resizer-linux-x86_64
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/x86_64-unknown-linux-musl/release/telegram_sticker_batch_resizer-linux-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos-x86_64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
          use-cross: true

      - run: mv target/release/telegram_sticker_batch_resizer target/release/telegram_sticker_batch_resizer-macos-x86_64
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/telegram_sticker_batch_resizer-macos-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows-x86_64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
          use-cross: true
        env:
          RUSTFLAGS: '-Ctarget-feature=+crt-static'

      - run: Rename-Item target/release/telegram_sticker_batch_resizer.exe telegram_sticker_batch_resizer-windows-x86_64.exe
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/telegram_sticker_batch_resizer-windows-x86_64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
